extends Node

enum DISASTER {RAIN, METEOR, WIND}

enum WEAPON {DAGGER, SWORD, SPEAR, HAMMER, PISTOL, SHURIKEN}
enum HAMMMER {NORMAL, BOOMER, SPIKE, BETTER, AREA}
enum AERIAL {NONE, AIR_DASH, DOUBLE_JUMP, HOOK, JET}
enum AURA {MORE_DAMAGE, MORE_HAMMER, ALL_DAMAGE, ALL_HAMMER, FAST_MOVE, FAST_GOLDHP, FAST_GOLDSPAWN}

const GRAVITY = 15

var difficulty = 0
