extends Node

enum DISASTER {RAIN, METEOR, WIND}

enum WEAPON {DAGGER, SWORD, SPEAR, HAMMER, PISTOL, SHURIKEN}
enum HAMMER {NORMAL, BOOMER, SPIKE, BETTER, AREA}
enum AERIAL {NONE, AIR_DASH, DOUBLE_JUMP, HOOK, JET}
enum AURA {MORE_DAMAGE, MORE_HAMMER, ALL_DAMAGE, ALL_HAMMER, FAST_MOVE, FAST_GOLDHP, FAST_GOLDSPAWN}

const GRAVITY = 800

var difficulty = 0

const weapon_sprite_index = {
	WEAPON.DAGGER: 22,
	WEAPON.SWORD: 0,
	WEAPON.SPEAR: 1,
	WEAPON.HAMMER: 2,
	WEAPON.PISTOL: 3,
	WEAPON.SHURIKEN: 4,
}

const hammer_sprite_index = {
	HAMMER.NORMAL: 5,
	HAMMER.BOOMER: 6,
	HAMMER.SPIKE: 7,
	HAMMER.BETTER: 8,
	HAMMER.AREA: 9,
}

const aerial_sprite_index = {
	AERIAL.NONE: 11,
	AERIAL.AIR_DASH: 10,
	AERIAL.DOUBLE_JUMP: 12,
	AERIAL.HOOK: 13,
	AERIAL.JET: 14
}

const aura_sprite_index = {
	AURA.MORE_DAMAGE: 15,
	AURA.MORE_HAMMER: 17,
	AURA.ALL_DAMAGE: 16,
	AURA.ALL_HAMMER: 18,
	AURA.FAST_MOVE: 19,
	AURA.FAST_GOLDHP: 20,
	AURA.FAST_GOLDSPAWN: 21,
}
